---
- name: Sysctl settings (disable IPv6)
  hosts: all
  gather_facts: true
  become: yes

  tasks:

    - ansible.posix.sysctl:
        name: net.ipv6.conf.all.disable_ipv6
        value: '1'
        sysctl_set: true
        state: present
        reload: true

    - ansible.posix.sysctl:
        name: net.ipv6.conf.default.disable_ipv6
        value: '1'
        sysctl_set: true
        state: present
        reload: true
